/** Added Files **/
export const ADD_CONTRACT = 'ADD_CONTRACT';

export const UPDATE_CONTRACT = 'UPDATE_CONTRACT';

export const REFRESH_CONTRACT = 'REFRESH_CONTRACT';

export const REMOVE_CONTRACT = 'REMOVE_CONTRACT';

export const REMOVE_ALL_CONTRACTS = 'REMOVE_ALL_CONTRACTS';